events {

}

http {
     server {
     	    listen 80;
	    server_name takitaga.42.fr;
	    return 301 https://$host$request_uri;
	    }
	    
     server {
     	    listen	443 ssl;
	    server_name takitaga.42.fr;

	    ssl_certificate	/etc/nginx/ssl/takitaga.crt;
	    ssl_certificate_key	/etc/nginx/ssl/takitaga.key;
	    ssl_protocols	TLSv1.2 TLSv1.3;
	    }
}
