events {

}

http {
     server {
     	    listen 80;
	    server_name takitaga.42.fr;
	    return 301 https://$host$request_uri;
     }
	    
     server {
      	    listen	443 ssl;
	    server_name takitaga.42.fr;

	    ssl_certificate	/etc/nginx/ssl/takitaga.crt;
	    ssl_certificate_key	/etc/nginx/ssl/takitaga.key;
	    ssl_protocols	TLSv1.2 TLSv1.3;
	    
	    root /var/www/html;
	    index index.php index.html;
	    
	    location / {
	        try_files $uri $uri/ /index.php?$args;
	    }
	    
	    location ~ .*\.(jpg|jpeg|gif|png|css|js|ico|woff)$ {
	    	expires 1h;
	    }
	    
	    location ~ \.php$ {
	        fastcgi_pass wordpress:9000;
	        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	        include fastcgi_params;
	    }
      }
}
