services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception-network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception-network
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always

volumes:
  mariadb-volume:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /home/takitaga/data/mariadb
      o: bind
  wordpress-volume:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      device: /home/takitaga/data/wordpress
      o: bind

networks:
  inception-network:
    driver: bridge
