services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception-network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: defaultdb
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
      MARIADB_ROOT_PASSWORD: rootpass
      TZ: Asia/Tokyo
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - mariadb-volume:/var/lib/mysql

volumes:
  mariadb-volume:
    name: mariadb-data
    driver: local

networks:
  inception-network:
